### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by cptcrunchy** [metalwarrior665/actor-google-sheets#10]
Please see the error log below:

```
2020-01-21T10:20:20.144Z ERROR: The function passed to Apify.main() threw an exception:
2020-01-21T10:20:20.146Z   Error: WRONG INPUT! - datasetId field needs to be a string with 17 characters!
2020-01-21T10:20:20.147Z     at module.exports (/home/myuser/src/validate-parse-input.js:28:15)
2020-01-21T10:20:20.149Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-01-21T10:20:20.151Z npm ERR! code ELIFECYCLE
2020-01-21T10:20:20.153Z npm ERR! errno 91
2020-01-21T10:20:20.155Z npm ERR! actor-google-spreadsheet@0.0.1 start: `node src/main.js`
2020-01-21T10:20:20.156Z npm ERR! Exit status 91
2020-01-21T10:20:20.158Z npm ERR! 
2020-01-21T10:20:20.162Z npm ERR! Failed at the actor-google-spreadsheet@0.0.1 start script.
2020-01-21T10:20:20.164Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-21T10:20:20.165Z```

No changes have been made to the task

**Comment by metalwarrior665** [comment]
There has been breaking change, you need to rename 
```datasetOrExecutionId```
in the input to
```datasetId```

I'm sorry for this, in the future, these breaking changes will not be propagated to old users.
